/var/lib/docker/volumes/abap-deploy_activity_logs/_data/activity.log {
    daily
    maxsize 10M
    rotate 14
    missingok
    notifempty
    compress
    delaycompress
    dateext
    copytruncate
}
