CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL CHECK (
        LENGTH(BTRIM(username)) > 0
    ),
    password_hash TEXT NOT NULL CHECK (
        LENGTH(BTRIM(password_hash)) > 0
    ),
    role TEXT NOT NULL CHECK (
        role IN ('admin', 'viewer')
    ),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_unique
ON users (LOWER(username));

CREATE TABLE IF NOT EXISTS employees (
    employee_id TEXT PRIMARY KEY CHECK (
        LENGTH(BTRIM(employee_id)) > 0
    ),
    name TEXT NOT NULL CHECK (
        LENGTH(BTRIM(name)) > 0
    ),
    department TEXT NOT NULL,
    position TEXT NOT NULL,
    country TEXT NOT NULL,
    salary BIGINT NOT NULL CHECK (
        salary > 0
    ),
    email TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    years_of_experience INTEGER NOT NULL CHECK (
        years_of_experience >= 0
    ),
    company TEXT NOT NULL,
    employment_status TEXT NOT NULL,
    performance_score INTEGER NOT NULL CHECK (
        performance_score BETWEEN 1 AND 5
    )
);

CREATE TABLE IF NOT EXISTS workflows (
    workflow_id TEXT PRIMARY KEY CHECK (
        LENGTH(BTRIM(workflow_id)) > 0
    ),
    name TEXT NOT NULL CHECK (
        LENGTH(BTRIM(name)) > 0
    ),
    description TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'draft' CHECK (
        status IN ('draft', 'active', 'inactive')
    ),
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (created_by_user_id)
        REFERENCES users(user_id)
);

CREATE INDEX IF NOT EXISTS workflows_status_index
ON workflows (status);

CREATE TABLE IF NOT EXISTS workflow_tasks (
    task_id TEXT PRIMARY KEY CHECK (
        LENGTH(BTRIM(task_id)) > 0
    ),
    workflow_id TEXT NOT NULL,
    sequence_number BIGINT NOT NULL CHECK (
        sequence_number > 0
    ),
    title TEXT NOT NULL CHECK (
        LENGTH(BTRIM(title)) > 0
    ),
    instructions TEXT NOT NULL DEFAULT '',
    task_type TEXT NOT NULL DEFAULT 'manual' CHECK (
        task_type IN ('manual')
    ),
    is_required BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    UNIQUE (workflow_id, sequence_number),
    FOREIGN KEY (workflow_id)
        REFERENCES workflows(workflow_id)
);

CREATE INDEX IF NOT EXISTS workflow_tasks_order_index
ON workflow_tasks (workflow_id, sequence_number);

CREATE TABLE IF NOT EXISTS workflow_schedules (
    schedule_id TEXT PRIMARY KEY,
    workflow_id TEXT NOT NULL,
    schedule_type TEXT NOT NULL CHECK (
        schedule_type IN ('manual', 'daily', 'weekly')
    ),
    scheduled_time TEXT,
    day_of_week TEXT CHECK (
        day_of_week IS NULL OR day_of_week IN (
            'monday', 'tuesday', 'wednesday', 'thursday',
            'friday', 'saturday', 'sunday'
        )
    ),
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (workflow_id)
        REFERENCES workflows(workflow_id),
    FOREIGN KEY (created_by_user_id)
        REFERENCES users(user_id),
    CHECK (
        (schedule_type = 'manual'
            AND scheduled_time IS NULL
            AND day_of_week IS NULL)
        OR
        (schedule_type = 'daily'
            AND scheduled_time ~
                '^([01][0-9]|2[0-3]):[0-5][0-9]$'
            AND day_of_week IS NULL)
        OR
        (schedule_type = 'weekly'
            AND scheduled_time ~
                '^([01][0-9]|2[0-3]):[0-5][0-9]$'
            AND day_of_week IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS workflow_schedules_workflow_index
ON workflow_schedules (workflow_id, is_enabled);

CREATE TABLE IF NOT EXISTS workflow_schedule_occurrences (
    occurrence_id TEXT PRIMARY KEY,
    schedule_id TEXT NOT NULL,
    workflow_id TEXT NOT NULL,
    scheduled_for_utc TIMESTAMPTZ NOT NULL,
    claimed_at TIMESTAMPTZ NOT NULL,
    UNIQUE (schedule_id, scheduled_for_utc),
    FOREIGN KEY (schedule_id)
        REFERENCES workflow_schedules(schedule_id),
    FOREIGN KEY (workflow_id)
        REFERENCES workflows(workflow_id)
);

CREATE INDEX IF NOT EXISTS schedule_occurrences_workflow_index
ON workflow_schedule_occurrences (
    workflow_id,
    scheduled_for_utc
);

CREATE TABLE IF NOT EXISTS workflow_executions (
    execution_id TEXT PRIMARY KEY CHECK (
        LENGTH(BTRIM(execution_id)) > 0
    ),
    workflow_id TEXT NOT NULL,
    workflow_name TEXT NOT NULL CHECK (
        LENGTH(BTRIM(workflow_name)) > 0
    ),
    trigger_type TEXT NOT NULL DEFAULT 'manual' CHECK (
        trigger_type IN ('manual', 'schedule')
    ),
    schedule_occurrence_id TEXT UNIQUE,
    status TEXT NOT NULL CHECK (
        status IN ('running', 'completed', 'failed')
    ),
    started_by_user_id BIGINT,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    result_summary TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (workflow_id)
        REFERENCES workflows(workflow_id),
    FOREIGN KEY (started_by_user_id)
        REFERENCES users(user_id),
    FOREIGN KEY (schedule_occurrence_id)
        REFERENCES workflow_schedule_occurrences(occurrence_id),
    CHECK (
        (
            trigger_type = 'manual'
            AND started_by_user_id IS NOT NULL
            AND schedule_occurrence_id IS NULL
        )
        OR (
            trigger_type = 'schedule'
            AND schedule_occurrence_id IS NOT NULL
        )
    ),
    CHECK (
        (
            status = 'running'
            AND finished_at IS NULL
        )
        OR (
            status IN ('completed', 'failed')
            AND finished_at IS NOT NULL
        )
    )
);

CREATE INDEX IF NOT EXISTS workflow_executions_history_index
ON workflow_executions (
    workflow_id,
    started_at DESC
);

CREATE TABLE IF NOT EXISTS workflow_task_executions (
    task_execution_id TEXT PRIMARY KEY CHECK (
        LENGTH(BTRIM(task_execution_id)) > 0
    ),
    execution_id TEXT NOT NULL,
    task_id TEXT NOT NULL,
    sequence_number BIGINT NOT NULL CHECK (
        sequence_number > 0
    ),
    task_title TEXT NOT NULL CHECK (
        LENGTH(BTRIM(task_title)) > 0
    ),
    status TEXT NOT NULL CHECK (
        status IN ('running', 'completed', 'failed')
    ),
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    result_summary TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (execution_id)
        REFERENCES workflow_executions(execution_id),
    CHECK (
        (
            status = 'running'
            AND finished_at IS NULL
        )
        OR (
            status IN ('completed', 'failed')
            AND finished_at IS NOT NULL
        )
    )
);

CREATE INDEX IF NOT EXISTS task_executions_history_index
ON workflow_task_executions (
    execution_id,
    sequence_number
);