"""Portfolio-safe invoice PDF generation with no external provider calls."""

from io import BytesIO

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import letter
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.pdfgen import canvas


def _money(cents: int, currency: str) -> str:
    return f"{currency} {cents / 100:,.2f}"


def generate_invoice_pdf(invoice: dict, customer: dict, line_items: list[dict]) -> bytes:
    """Create a concise, static PDF from immutable invoice line snapshots."""
    buffer = BytesIO()
    page = canvas.Canvas(buffer, pagesize=letter, pageCompression=1)
    width, height = letter
    navy = HexColor("#17324D")
    muted = HexColor("#52616B")
    page.setFillColor(navy)
    page.setFont("Helvetica-Bold", 24)
    page.drawString(54, height - 62, "ABAP")
    page.setFont("Helvetica", 10)
    page.drawString(54, height - 78, "AI Business Automation Platform")
    page.setFont("Helvetica-Bold", 24)
    page.drawRightString(width - 54, height - 62, "INVOICE")
    page.setFont("Helvetica", 10)
    page.drawRightString(width - 54, height - 78, invoice["invoice_number"])
    page.setStrokeColor(HexColor("#D6DCE1"))
    page.line(54, height - 94, width - 54, height - 94)

    page.setFillColor(muted)
    page.setFont("Helvetica-Bold", 9)
    page.drawString(54, height - 122, "BILL TO")
    page.drawString(350, height - 122, "INVOICE DETAILS")
    page.setFillColor(navy)
    page.setFont("Helvetica", 10)
    page.drawString(54, height - 139, customer["name"][:80])
    if customer["company"]:
        page.drawString(54, height - 154, customer["company"][:80])
    if customer["email"]:
        page.drawString(54, height - 169, customer["email"][:80])
    page.drawString(350, height - 139, f"Status: {invoice['status'].title()}")
    page.drawString(350, height - 154, f"Due date: {invoice['due_date'] or 'On receipt'}")
    page.drawString(350, height - 169, f"Currency: {invoice['currency']}")

    y = height - 215
    page.setFillColor(navy)
    page.rect(54, y, width - 108, 22, stroke=0, fill=1)
    page.setFillColor(HexColor("#FFFFFF"))
    page.setFont("Helvetica-Bold", 9)
    page.drawString(62, y + 7, "DESCRIPTION")
    page.drawRightString(405, y + 7, "QUANTITY")
    page.drawRightString(485, y + 7, "UNIT PRICE")
    page.drawRightString(width - 62, y + 7, "TOTAL")
    y -= 24
    page.setFont("Helvetica", 9)
    for line in line_items:
        page.setFillColor(navy)
        page.drawString(62, y, line["description"][:58])
        page.drawRightString(405, y, str(line["quantity"]))
        page.drawRightString(485, y, _money(line["unit_price_cents"], invoice["currency"]))
        page.drawRightString(width - 62, y, _money(line["line_total_cents"], invoice["currency"]))
        y -= 22
    page.setStrokeColor(HexColor("#D6DCE1"))
    page.line(350, y - 4, width - 54, y - 4)
    page.setFillColor(muted)
    page.setFont("Helvetica", 9)
    page.drawString(350, y - 22, "Subtotal")
    page.drawRightString(width - 62, y - 22, _money(invoice["subtotal_cents"], invoice["currency"]))
    page.drawString(350, y - 39, "Tax")
    page.drawRightString(width - 62, y - 39, _money(invoice["tax_cents"], invoice["currency"]))
    page.setFillColor(navy)
    page.setFont("Helvetica-Bold", 12)
    page.drawString(350, y - 62, "TOTAL DUE")
    page.drawRightString(width - 62, y - 62, _money(invoice["total_cents"], invoice["currency"]))
    page.setFillColor(muted)
    page.setFont("Helvetica", 8)
    page.drawString(54, 48, "This portfolio-safe invoice is generated from immutable ABAP invoice snapshots.")
    page.drawRightString(width - 54, 48, "Generated by ABAP")
    page.showPage()
    page.save()
    return buffer.getvalue()
